import Ionicons from "@expo/vector-icons/Ionicons";

type IconName = React.ComponentProps<typeof Ionicons>["name"];

export const categories: {
  [key: string]: { id: number; name: string; icon?: IconName };
} = {
  "sports": { id: 1, name: "Sports", icon: "football" },
  "football": { id: 2, name: "Football", icon: "football-outline" },
  "basketball": { id: 3, name: "Basketball", icon: "basketball" },
  "tennis": { id: 4, name: "Tennis", icon: "tennisball" },
  "motorsports": { id: 5, name: "Motorsports", icon: "car-sport" },
  "combat sports": { id: 6, name: "Combat Sports", icon: "fitness" },
  "movies": { id: 7, name: "Movies", icon: "film" },
  "action movies": { id: 8, name: "Action Movies", icon: "flame" },
  "comedy movies": { id: 9, name: "Comedy Movies", icon: "happy" },
  "drama movies": { id: 10, name: "Drama Movies", icon: "sad" },
  "horror movies": { id: 11, name: "Horror Movies", icon: "skull" },
  "sci-fi movies": { id: 12, name: "Sci-Fi Movies", icon: "planet" },
  "romance movies": { id: 13, name: "Romance Movies", icon: "heart" },
  "tv shows": { id: 14, name: "TV Shows", icon: "tv" },
  "drama series": { id: 15, name: "Drama Series", icon: "tv-outline" },
  "comedy series": { id: 16, name: "Comedy Series", icon: "happy-outline" },
  news: { id: 17, name: "News", icon: "newspaper" },
  "international news": { id: 18, name: "International News", icon: "globe" },
  "local news": { id: 19, name: "Local News", icon: "location" },
  weather: { id: 20, name: "Weather", icon: "partly-sunny" },
  business: { id: 21, name: "Business", icon: "trending-up" },
  politics: { id: 22, name: "Politics", icon: "megaphone" },
  documentaries: { id: 23, name: "Documentaries", icon: "earth" },
  "nature & wildlife": { id: 24, name: "Nature & Wildlife", icon: "leaf" },
  history: { id: 25, name: "History", icon: "time" },
  science: { id: 26, name: "Science", icon: "flask" },
  technology: { id: 27, name: "Technology", icon: "hardware-chip" },
  space: { id: 28, name: "Space", icon: "rocket" },
  kids: { id: 29, name: "Kids", icon: "balloon" },
  cartoons: { id: 30, name: "Cartoons", icon: "color-palette" },
  "educational kids": { id: 31, name: "Educational Kids", icon: "school" },
  music: { id: 32, name: "Music", icon: "musical-notes" },
  concerts: { id: 33, name: "Concerts", icon: "mic" },
  "music videos": { id: 34, name: "Music Videos", icon: "play" },
  radio: { id: 35, name: "Radio", icon: "radio" },
  entertainment: { id: 36, name: "Entertainment", icon: "game-controller" },
  "reality tv": { id: 37, name: "Reality TV", icon: "videocam" },
  "game shows": { id: 38, name: "Game Shows", icon: "trophy" },
  "talk shows": { id: 39, name: "Talk Shows", icon: "chatbubbles" },
  "variety shows": { id: 40, name: "Variety Shows", icon: "star" },
  cooking: { id: 41, name: "Cooking", icon: "restaurant" },
  "food & drink": { id: 42, name: "Food & Drink", icon: "pizza" },
  travel: { id: 43, name: "Travel", icon: "airplane" },
  discovery: { id: 44, name: "Discovery", icon: "compass" },
  adventure: { id: 45, name: "Adventure", icon: "map" },
  lifestyle: { id: 46, name: "Lifestyle", icon: "flower" },
  fashion: { id: 47, name: "Fashion", icon: "shirt" },
  beauty: { id: 48, name: "Beauty", icon: "sparkles" },
  "home & garden": { id: 49, name: "Home & Garden", icon: "home" },
  gardening: { id: 50, name: "Gardening", icon: "rose" },
  "health & fitness": {
    id: 51,
    name: "Health & Fitness",
    icon: "fitness-outline",
  },
  religious: { id: 52, name: "Religious", icon: "book" },
  spiritual: { id: 53, name: "Spiritual", icon: "moon" },
  "business & finance": {
    id: 54,
    name: "Business & Finance",
    icon: "briefcase",
  },
  finance: { id: 55, name: "Finance", icon: "cash" },
  "real estate": { id: 56, name: "Real Estate", icon: "business" },
  automotive: { id: 57, name: "Automotive", icon: "car" },
  culture: { id: 58, name: "Culture", icon: "library" },
  arts: { id: 59, name: "Arts", icon: "brush" },
  theater: { id: 60, name: "Theater", icon: "images" },
  "classic movies": { id: 61, name: "Classic Movies", icon: "film-outline" },
  anime: { id: 62, name: "Anime", icon: "paw" },
  gaming: { id: 63, name: "Gaming", icon: "game-controller-outline" },
  esports: { id: 64, name: "Esports", icon: "trophy-outline" },
  adult: { id: 65, name: "Adult", icon: "lock-closed" },
  "24/7": { id: 66, name: "24/7", icon: "infinite" },
  regional: { id: 67, name: "Regional", icon: "flag" },
  international: { id: 68, name: "International", icon: "globe-outline" },
  premium: { id: 69, name: "Premium", icon: "diamond" },
  general: { id: 70, name: "General", icon: "apps" },
  all: { id: 71, name: "All", icon: "grid" },
  animation: { id: 72, name: "Animation", icon: "color-fill" },
  family: { id: 73, name: "Family", icon: "people" },
  interactive: { id: 74, name: "Interactive", icon: "hand-left" },
  legislative: { id: 75, name: "Legislative", icon: "document-text" },
  outdoor: { id: 76, name: "Outdoor", icon: "sunny" },
  public: { id: 77, name: "Public", icon: "people-circle" },
  relax: { id: 78, name: "Relax", icon: "bed" },
  shop: { id: 79, name: "Shop", icon: "cart" },
  nature: { id: 80, name: "Nature", icon: "leaf" },
  local: { id: 81, name: "Local", icon: "location" },
  archive: { id: 82, name: "Archive", icon: "albums" },
  economy: { id: 83, name: "Economy", icon: "trending-up" },
  info: { id: 84, name: "Info", icon: "information-circle" },
  youth: { id: 85, name: "Youth", icon: "people-outline" },
  reports: { id: 87, name: "Reports", icon: "stats-chart" },
  combat: { id: 88, name: "Combat", icon: "fitness" },
  action: { id: 89, name: "Action", icon: "flame" },
  comedy: { id: 90, name: "Comedy", icon: "happy" },
  drama: { id: 91, name: "Drama", icon: "sad" },
  horror: { id: 92, name: "Horror", icon: "skull" },
  "sci-fi": { id: 93, name: "Sci-Fi", icon: "planet" },
  "sci-fiction": { id: 94, name: "Sci-Fiction", icon: "planet" },
  romance: { id: 95, name: "Romance", icon: "heart" },
  series: { id: 96, name: "Series", icon: "tv-outline" },
  documentary: { id: 97, name: "Documentary", icon: "earth" },
  education: { id: 98, name: "Education", icon: "school" },
  games: { id: 99, name: "Games", icon: "game-controller" },
  auto: { id: 100, name: "Auto", icon: "car" },
  classic: { id: 101, name: "Classic", icon: "film-outline" },
  afghanistan: { id: 102, name: "🇦🇫", icon: undefined },
  albania: { id: 103, name: "🇦🇱", icon: undefined },
  algeria: { id: 104, name: "🇩🇿", icon: undefined },
  andorra: { id: 105, name: "🇦🇩", icon: undefined },
  angola: { id: 106, name: "🇦🇴", icon: undefined },
  "antigua and barbuda": { id: 107, name: "🇦🇬", icon: undefined },
  argentina: { id: 108, name: "🇦🇷", icon: undefined },
  armenia: { id: 109, name: "🇦🇲", icon: undefined },
  australia: { id: 110, name: "🇦🇺", icon: undefined },
  austria: { id: 111, name: "🇦🇹", icon: undefined },
  azerbaijan: { id: 112, name: "🇦🇿", icon: undefined },
  bahamas: { id: 113, name: "🇧🇸", icon: undefined },
  bahrain: { id: 114, name: "🇧🇭", icon: undefined },
  bangladesh: { id: 115, name: "🇧🇩", icon: undefined },
  barbados: { id: 116, name: "🇧🇧", icon: undefined },
  belarus: { id: 117, name: "🇧🇾", icon: undefined },
  belgium: { id: 118, name: "🇧🇪", icon: undefined },
  belize: { id: 119, name: "🇧🇿", icon: undefined },
  benin: { id: 120, name: "🇧🇯", icon: undefined },
  bhutan: { id: 121, name: "🇧🇹", icon: undefined },
  bolivia: { id: 122, name: "🇧🇴", icon: undefined },
  "bosnia and herzegovina": { id: 123, name: "🇧🇦", icon: undefined },
  botswana: { id: 124, name: "🇧🇼", icon: undefined },
  brazil: { id: 125, name: "🇧🇷", icon: undefined },
  brunei: { id: 126, name: "🇧🇳", icon: undefined },
  bulgaria: { id: 127, name: "🇧🇬", icon: undefined },
  "burkina faso": { id: 128, name: "🇧🇫", icon: undefined },
  burundi: { id: 129, name: "🇧🇮", icon: undefined },
  "cabo verde": { id: 130, name: "🇨🇻", icon: undefined },
  cambodia: { id: 131, name: "🇰🇭", icon: undefined },
  cameroon: { id: 132, name: "🇨🇲", icon: undefined },
  canada: { id: 133, name: "🇨🇦", icon: undefined },
  "central african republic": { id: 134, name: "🇨🇫", icon: undefined },
  chad: { id: 135, name: "🇹🇩", icon: undefined },
  chile: { id: 136, name: "🇨🇱", icon: undefined },
  china: { id: 137, name: "🇨🇳", icon: undefined },
  colombia: { id: 138, name: "🇨🇴", icon: undefined },
  comoros: { id: 139, name: "🇰🇲", icon: undefined },
  "republic of the congo": { id: 140, name: "🇨🇬", icon: undefined },
  "costa rica": { id: 141, name: "🇨🇷", icon: undefined },
  croatia: { id: 142, name: "🇭🇷", icon: undefined },
  cuba: { id: 143, name: "🇨🇺", icon: undefined },
  cyprus: { id: 144, name: "🇨🇾", icon: undefined },
  "czech republic": { id: 145, name: "🇨🇿", icon: undefined },
  denmark: { id: 146, name: "🇩🇰", icon: undefined },
  djibouti: { id: 147, name: "🇩🇯", icon: undefined },
  dominica: { id: 148, name: "🇩🇲", icon: undefined },
  "dominican republic": { id: 149, name: "🇩🇴", icon: undefined },
  "democratic republic of the congo": { id: 150, name: "🇨🇩", icon: undefined },
  ecuador: { id: 151, name: "🇪🇨", icon: undefined },
  egypt: { id: 152, name: "🇪🇬", icon: undefined },
  "el salvador": { id: 153, name: "🇸🇻", icon: undefined },
  "equatorial guinea": { id: 154, name: "🇬🇶", icon: undefined },
  eritrea: { id: 155, name: "🇪🇷", icon: undefined },
  estonia: { id: 156, name: "🇪🇪", icon: undefined },
  eswatini: { id: 157, name: "🇸🇿", icon: undefined },
  ethiopia: { id: 158, name: "🇪🇹", icon: undefined },
  fiji: { id: 159, name: "🇫🇯", icon: undefined },
  finland: { id: 160, name: "🇫🇮", icon: undefined },
  france: { id: 161, name: "🇫🇷", icon: undefined },
  gabon: { id: 162, name: "🇬🇦", icon: undefined },
  gambia: { id: 163, name: "🇬🇲", icon: undefined },
  georgia: { id: 164, name: "🇬🇪", icon: undefined },
  germany: { id: 165, name: "🇩🇪", icon: undefined },
  ghana: { id: 166, name: "🇬🇭", icon: undefined },
  greece: { id: 167, name: "🇬🇷", icon: undefined },
  grenada: { id: 168, name: "🇬🇩", icon: undefined },
  guatemala: { id: 169, name: "🇬🇹", icon: undefined },
  guinea: { id: 170, name: "🇬🇳", icon: undefined },
  "guinea-bissau": { id: 171, name: "🇬🇼", icon: undefined },
  guyana: { id: 172, name: "🇬🇾", icon: undefined },
  haiti: { id: 173, name: "🇭🇹", icon: undefined },
  honduras: { id: 174, name: "🇭🇳", icon: undefined },
  "hong kong": { id: 175, name: "🇭🇰", icon: undefined },
  hungary: { id: 176, name: "🇭🇺", icon: undefined },
  iceland: { id: 177, name: "🇮🇸", icon: undefined },
  india: { id: 178, name: "🇮🇳", icon: undefined },
  indonesia: { id: 179, name: "🇮🇩", icon: undefined },
  iran: { id: 180, name: "🇮🇷", icon: undefined },
  iraq: { id: 181, name: "🇮🇶", icon: undefined },
  ireland: { id: 182, name: "🇮🇪", icon: undefined },
  israel: { id: 183, name: "🇮🇱", icon: undefined },
  italy: { id: 184, name: "🇮🇹", icon: undefined },
  "ivory coast": { id: 185, name: "🇨🇮", icon: undefined },
  jamaica: { id: 186, name: "🇯🇲", icon: undefined },
  japan: { id: 187, name: "🇯🇵", icon: undefined },
  jordan: { id: 188, name: "🇯🇴", icon: undefined },
  kazakhstan: { id: 189, name: "🇰🇿", icon: undefined },
  kenya: { id: 190, name: "🇰🇪", icon: undefined },
  kiribati: { id: 191, name: "🇰🇮", icon: undefined },
  kosovo: { id: 192, name: "🇽🇰", icon: undefined },
  kuwait: { id: 193, name: "🇰🇼", icon: undefined },
  kyrgyzstan: { id: 194, name: "🇰🇬", icon: undefined },
  laos: { id: 195, name: "🇱🇦", icon: undefined },
  latvia: { id: 196, name: "🇱🇻", icon: undefined },
  lebanon: { id: 197, name: "🇱🇧", icon: undefined },
  lesotho: { id: 198, name: "🇱🇸", icon: undefined },
  liberia: { id: 199, name: "🇱🇷", icon: undefined },
  libya: { id: 200, name: "🇱🇾", icon: undefined },
  liechtenstein: { id: 201, name: "🇱🇮", icon: undefined },
  lithuania: { id: 202, name: "🇱🇹", icon: undefined },
  luxembourg: { id: 203, name: "🇱🇺", icon: undefined },
  madagascar: { id: 204, name: "🇲🇬", icon: undefined },
  malawi: { id: 205, name: "🇲🇼", icon: undefined },
  malaysia: { id: 206, name: "🇲🇾", icon: undefined },
  maldives: { id: 207, name: "🇲🇻", icon: undefined },
  mali: { id: 208, name: "🇲🇱", icon: undefined },
  malta: { id: 209, name: "🇲🇹", icon: undefined },
  "marshall islands": { id: 210, name: "🇲🇭", icon: undefined },
  mauritania: { id: 211, name: "🇲🇷", icon: undefined },
  mauritius: { id: 212, name: "🇲🇺", icon: undefined },
  mexico: { id: 213, name: "🇲🇽", icon: undefined },
  micronesia: { id: 214, name: "🇫🇲", icon: undefined },
  moldova: { id: 215, name: "🇲🇩", icon: undefined },
  monaco: { id: 216, name: "🇲🇨", icon: undefined },
  mongolia: { id: 217, name: "🇲🇳", icon: undefined },
  montenegro: { id: 218, name: "🇲🇪", icon: undefined },
  morocco: { id: 219, name: "🇲🇦", icon: undefined },
  mozambique: { id: 220, name: "🇲🇿", icon: undefined },
  myanmar: { id: 221, name: "🇲🇲", icon: undefined },
  namibia: { id: 222, name: "🇳🇦", icon: undefined },
  nauru: { id: 223, name: "🇳🇷", icon: undefined },
  nepal: { id: 224, name: "🇳🇵", icon: undefined },
  netherlands: { id: 225, name: "🇳🇱", icon: undefined },
  "new zealand": { id: 226, name: "🇳🇿", icon: undefined },
  "nicaragua": { id: 227, name: "🇳🇮", icon: undefined },
  "niger": { id: 228, name: "🇳🇪", icon: undefined },
  "nigeria": { id: 229, name: "🇳🇬", icon: undefined },
  "north korea": { id: 230, name: "🇰🇵", icon: undefined },
  "north macedonia": { id: 231, name: "🇲🇰", icon: undefined },
  "norway": { id: 232, name: "🇳🇴", icon: undefined },
  "oman": { id: 233, name: "🇴🇲", icon: undefined },
  "pakistan": { id: 234, name: "🇵🇰", icon: undefined },
  "palau": { id: 235, name: "🇵🇼", icon: undefined },
  "palestine": { id: 236, name: "🇵🇸", icon: undefined },
  panama: { id: 237, name: "🇵🇦", icon: undefined },
  "papua new guinea": { id: 238, name: "🇵🇬", icon: undefined },
  "paraguay": { id: 239, name: "🇵🇾", icon: undefined },
  peru: { id: 240, name: "🇵🇪", icon: undefined },
  philippines: { id: 241, name: "🇵🇭", icon: undefined },
  poland: { id: 242, name: "🇵🇱", icon: undefined },
  portugal: { id: 243, name: "🇵🇹", icon: undefined },
  qatar: { id: 244, name: "🇶🇦", icon: undefined },
  romania: { id: 245, name: "🇷🇴", icon: undefined },
  russia: { id: 246, name: "🇷🇺", icon: undefined },
  rwanda: { id: 247, name: "🇷🇼", icon: undefined },
  "saint kitts and nevis": { id: 248, name: "🇰🇳", icon: undefined },
  "saint lucia": { id: 249, name: "🇱🇨", icon: undefined },
  "saint vincent": { id: 250, name: "🇻🇨", icon: undefined },
  samoa: { id: 251, name: "🇼🇸", icon: undefined },
  "san marino": { id: 252, name: "🇸🇲", icon: undefined },
  "sao tome and principe": { id: 253, name: "🇸🇹", icon: undefined },
  "saudi arabia": { id: 254, name: "🇸🇦", icon: undefined },
  senegal: { id: 255, name: "🇸🇳", icon: undefined },
  serbia: { id: 256, name: "🇷🇸", icon: undefined },
  seychelles: { id: 257, name: "🇸🇨", icon: undefined },
  "sierra leone": { id: 258, name: "🇸🇱", icon: undefined },
  singapore: { id: 259, name: "🇸🇬", icon: undefined },
  slovakia: { id: 260, name: "🇸🇰", icon: undefined },
  slovenia: { id: 261, name: "🇸🇮", icon: undefined },
  "solomon islands": { id: 262, name: "🇸🇧", icon: undefined },
  somalia: { id: 263, name: "🇸🇴", icon: undefined },
  "south africa": { id: 264, name: "🇿🇦", icon: undefined },
  "south korea": { id: 265, name: "🇰🇷", icon: undefined },
  "south sudan": { id: 266, name: "🇸🇸", icon: undefined },
  spain: { id: 267, name: "🇪🇸", icon: undefined },
  "sri lanka": { id: 268, name: "🇱🇰", icon: undefined },
  sudan: { id: 269, name: "🇸🇩", icon: undefined },
  suriname: { id: 270, name: "🇸🇷", icon: undefined },
  sweden: { id: 271, name: "🇸🇪", icon: undefined },
  switzerland: { id: 272, name: "🇨🇭", icon: undefined },
  syria: { id: 273, name: "🇸🇾", icon: undefined },
  taiwan: { id: 274, name: "🇹🇼", icon: undefined },
  tajikistan: { id: 275, name: "🇹🇯", icon: undefined },
  tanzania: { id: 276, name: "🇹🇿", icon: undefined },
  thailand: { id: 277, name: "🇹🇭", icon: undefined },
  "timor-leste": { id: 278, name: "🇹🇱", icon: undefined },
  togo: { id: 279, name: "🇹🇬", icon: undefined },
  tonga: { id: 280, name: "🇹🇴", icon: undefined },
  "trinidad and tobago": { id: 281, name: "🇹🇹", icon: undefined },
  tunisia: { id: 282, name: "🇹🇳", icon: undefined },
  turkey: { id: 283, name: "🇹🇷", icon: undefined },
  turkiye: { id: 283, name: "🇹🇷", icon: undefined },
  turkmenistan: { id: 284, name: "🇹🇲", icon: undefined },
  tuvalu: { id: 285, name: "🇹🇻", icon: undefined },
  uae: { id: 286, name: "🇦🇪", icon: undefined },
  uganda: { id: 287, name: "🇺🇬", icon: undefined },
  uk: { id: 288, name: "🇬🇧", icon: undefined },
  ukraine: { id: 289, name: "🇺🇦", icon: undefined },
  uruguay: { id: 290, name: "🇺🇾", icon: undefined },
  usa: { id: 291, name: "🇺🇸", icon: undefined },
  "united states": { id: 291, name: "🇺🇸", icon: undefined },
  uzbekistan: { id: 292, name: "🇺🇿", icon: undefined },
  vanuatu: { id: 293, name: "🇻🇺", icon: undefined },
  vatican: { id: 294, name: "🇻🇦", icon: undefined },
  "vatican city": { id: 294, name: "🇻🇦", icon: undefined },
  venezuela: { id: 295, name: "🇻🇪", icon: undefined },
  vietnam: { id: 296, name: "🇻🇳", icon: undefined },
  yemen: { id: 297, name: "🇾🇪", icon: undefined },
  zambia: { id: 298, name: "🇿🇲", icon: undefined },
  zimbabwe: { id: 299, name: "🇿🇼", icon: undefined },
  'united arab emirates': { id: 300, name: '🇦🇪', icon: undefined },
'united kingdom': { id: 301, name: '🇬🇧', icon: undefined },
'western sahara': { id: 302, name: '🇪🇭', icon: undefined },
'us virgin islands': { id: 303, name: '🇻🇮', icon: undefined },
'u.s. virgin islands': { id: 303, name: '🇻🇮', icon: undefined },
'sint maarten': { id: 304, name: '🇸🇽', icon: undefined },
'aruba': { id: 305, name: '🇦🇼', icon: undefined },
'bermuda': { id: 306, name: '🇧🇲', icon: undefined },
'bonaire': { id: 307, name: '🇧🇶', icon: undefined },
'british virgin islands': { id: 308, name: '🇻🇬', icon: undefined },
'cape verde': { id: 309, name: '🇨🇻', icon: undefined },
'curacao': { id: 310, name: '🇨🇼', icon: undefined },
'french guiana': { id: 311, name: '🇬🇫', icon: undefined },
'french polynesia': { id: 312, name: '🇵🇫', icon: undefined },
'guadeloupe': { id: 313, name: '🇬🇵', icon: undefined },
'guam': { id: 314, name: '🇬🇺', icon: undefined },
'guernsey': { id: 315, name: '🇬🇬', icon: undefined },
'macao': { id: 316, name: '🇲🇴', icon: undefined },
'martinique': { id: 317, name: '🇲🇶', icon: undefined },
'puerto rico': { id: 318, name: '🇵🇷', icon: undefined },
'reunion': { id: 319, name: '🇷🇪', icon: undefined },
  default: { id: 0, name: "Default", icon: "albums-outline" },
  undefined: { id: -1, name: "Undefined", icon: "albums-outline" },
};
