import Ionicons from "@expo/vector-icons/Ionicons";

type IconName = React.ComponentProps<typeof Ionicons>['name'];

export const categories : { [key: string]: { id: number; name: string; icon: IconName } } =  {
    'sports': { id: 1, name: 'Sports', icon: 'football' },
    'football': { id: 2, name: 'Football', icon: 'football-outline' },
    'basketball': { id: 3, name: 'Basketball', icon: 'basketball' },
    'tennis': { id: 4, name: 'Tennis', icon: 'tennisball' },
    'motorsports': { id: 5, name: 'Motorsports', icon: 'car-sport' },
    'combat sports': { id: 6, name: 'Combat Sports', icon: 'fitness' },
    'movies': { id: 7, name: 'Movies', icon: 'film' },
    'action movies': { id: 8, name: 'Action Movies', icon: 'flame' },
    'comedy movies': { id: 9, name: 'Comedy Movies', icon: 'happy' },
    'drama movies': { id: 10, name: 'Drama Movies', icon: 'sad' },
    'horror movies': { id: 11, name: 'Horror Movies', icon: 'skull' },
    'sci-fi movies': { id: 12, name: 'Sci-Fi Movies', icon: 'planet' },
    'romance movies': { id: 13, name: 'Romance Movies', icon: 'heart' },
    'tv shows': { id: 14, name: 'TV Shows', icon: 'tv' },
    'drama series': { id: 15, name: 'Drama Series', icon: 'tv-outline' },
    'comedy series': { id: 16, name: 'Comedy Series', icon: 'happy-outline' },
    'news': { id: 17, name: 'News', icon: 'newspaper' },
    'international news': { id: 18, name: 'International News', icon: 'globe' },
    'local news': { id: 19, name: 'Local News', icon: 'location' },
    'weather': { id: 20, name: 'Weather', icon: 'partly-sunny' },
    'business': { id: 21, name: 'Business', icon: 'trending-up' },
    'politics': { id: 22, name: 'Politics', icon: 'megaphone' },
    'documentaries': { id: 23, name: 'Documentaries', icon: 'earth' },
    'nature & wildlife': { id: 24, name: 'Nature & Wildlife', icon: 'leaf' },
    'history': { id: 25, name: 'History', icon: 'time' },
    'science': { id: 26, name: 'Science', icon: 'flask' },
    'technology': { id: 27, name: 'Technology', icon: 'hardware-chip' },
    'space': { id: 28, name: 'Space', icon: 'rocket' },
    'kids': { id: 29, name: 'Kids', icon: 'balloon' },
    'cartoons': { id: 30, name: 'Cartoons', icon: 'color-palette' },
    'educational kids': { id: 31, name: 'Educational Kids', icon: 'school' },
    'music': { id: 32, name: 'Music', icon: 'musical-notes' },
    'concerts': { id: 33, name: 'Concerts', icon: 'mic' },
    'music videos': { id: 34, name: 'Music Videos', icon: 'play' },
    'radio': { id: 35, name: 'Radio', icon: 'radio' },
    'entertainment': { id: 36, name: 'Entertainment', icon: 'game-controller' },
    'reality tv': { id: 37, name: 'Reality TV', icon: 'videocam' },
    'game shows': { id: 38, name: 'Game Shows', icon: 'trophy' },
    'talk shows': { id: 39, name: 'Talk Shows', icon: 'chatbubbles' },
    'variety shows': { id: 40, name: 'Variety Shows', icon: 'star' },
    'cooking': { id: 41, name: 'Cooking', icon: 'restaurant' },
    'food & drink': { id: 42, name: 'Food & Drink', icon: 'pizza' },
    'travel': { id: 43, name: 'Travel', icon: 'airplane' },
    'discovery': { id: 44, name: 'Discovery', icon: 'compass' },
    'adventure': { id: 45, name: 'Adventure', icon: 'map' },
    'lifestyle': { id: 46, name: 'Lifestyle', icon: 'flower' },
    'fashion': { id: 47, name: 'Fashion', icon: 'shirt' },
    'beauty': { id: 48, name: 'Beauty', icon: 'sparkles' },
    'home & garden': { id: 49, name: 'Home & Garden', icon: 'home' },
    'gardening': { id: 50, name: 'Gardening', icon: 'rose' },
    'health & fitness': { id: 51, name: 'Health & Fitness', icon: 'fitness-outline' },
    'religious': { id: 52, name: 'Religious', icon: 'book' },
    'spiritual': { id: 53, name: 'Spiritual', icon: 'moon' },
    'business & finance': { id: 54, name: 'Business & Finance', icon: 'briefcase' },
    'finance': { id: 55, name: 'Finance', icon: 'cash' },
    'real estate': { id: 56, name: 'Real Estate', icon: 'business' },
    'automotive': { id: 57, name: 'Automotive', icon: 'car' },
    'culture': { id: 58, name: 'Culture', icon: 'library' },
    'arts': { id: 59, name: 'Arts', icon: 'brush' },
    'theater': { id: 60, name: 'Theater', icon: 'images' },
    'classic movies': { id: 61, name: 'Classic Movies', icon: 'film-outline' },
    'anime': { id: 62, name: 'Anime', icon: 'paw' },
    'gaming': { id: 63, name: 'Gaming', icon: 'game-controller-outline' },
    'esports': { id: 64, name: 'Esports', icon: 'trophy-outline' },
    'adult': { id: 65, name: 'Adult', icon: 'lock-closed' },
    '24/7': { id: 66, name: '24/7', icon: 'infinite' },
    'regional': { id: 67, name: 'Regional', icon: 'flag' },
    'international': { id: 68, name: 'International', icon: 'globe-outline' },
    'premium': { id: 69, name: 'Premium', icon: 'diamond' },
    'general': { id: 70, name: 'General', icon: 'apps' },
    'all': { id: 71, name: 'All', icon: 'grid' },
    'animation': { id: 72, name: 'Animation', icon: 'color-fill' },
    'family': { id: 73, name: 'Family', icon: 'people' },
    'interactive': { id: 74, name: 'Interactive', icon: 'hand-left' },
    'legislative': { id: 75, name: 'Legislative', icon: 'document-text' },
    'outdoor': { id: 76, name: 'Outdoor', icon: 'sunny' },
    'public': { id: 77, name: 'Public', icon: 'people-circle' },
    'relax': { id: 78, name: 'Relax', icon: 'bed' },
    'shop': { id: 79, name: 'Shop', icon: 'cart' },
    'nature': { id: 80, name: 'Nature', icon: 'leaf' },
    'local': { id: 81, name: 'Local', icon: 'location' },
    'archive': { id: 82, name: 'Archive', icon: 'albums' },
    'economy': { id: 83, name: 'Economy', icon: 'trending-up' },
    'info': { id: 84, name: 'Info', icon: 'information-circle' },
    'youth': { id: 85, name: 'Youth', icon: 'people-outline' },
    'reports': { id: 87, name: 'Reports', icon: 'stats-chart' },
    'combat': { id: 88, name: 'Combat', icon: 'fitness' },
    'action': { id: 89, name: 'Action', icon: 'flame' },
    'comedy': { id: 90, name: 'Comedy', icon: 'happy' },
    'drama': { id: 91, name: 'Drama', icon: 'sad' },
    'horror': { id: 92, name: 'Horror', icon: 'skull' },
    'sci-fi': { id: 93, name: 'Sci-Fi', icon: 'planet' },
    'sci-fiction': { id: 94, name: 'Sci-Fiction', icon: 'planet' },
    'romance': { id: 95, name: 'Romance', icon: 'heart' },
    'series': { id: 96, name: 'Series', icon: 'tv-outline' },
    'documentary': { id: 97, name: 'Documentary', icon: 'earth' },
    'education': { id: 98, name: 'Education', icon: 'school' },
    'games': { id: 99, name: 'Games', icon: 'game-controller' },
    'auto': { id: 100, name: 'Auto', icon: 'car' },
    'classic': { id: 101, name: 'Classic', icon: 'film-outline' },
    'default': { id: 0, name: 'Default', icon: 'albums-outline' },
    'undefined': { id: -1, name: 'Undefined', icon: 'albums-outline' }
  };