/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/favorite` | `/favorite`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/settings/faq` | `/settings/faq`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(app)'}${'/(tabs)'}/home/category/[playlistId]` | `/home/category/[playlistId]`, params: Router.UnknownInputParams & { playlistId: string | number; } } | { pathname: `${'/(app)'}${'/(tabs)'}/home/category/channel/[categoryId]` | `/home/category/channel/[categoryId]`, params: Router.UnknownInputParams & { categoryId: string | number; } } | { pathname: `${'/(app)'}${'/(tabs)'}/home/form/[id]` | `/home/form/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/player/[id]` | `/player/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/favorite` | `/favorite`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/settings/faq` | `/settings/faq`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `${'/(app)'}${'/(tabs)'}/home/category/[playlistId]` | `/home/category/[playlistId]`, params: Router.UnknownOutputParams & { playlistId: string; } } | { pathname: `${'/(app)'}${'/(tabs)'}/home/category/channel/[categoryId]` | `/home/category/channel/[categoryId]`, params: Router.UnknownOutputParams & { categoryId: string; } } | { pathname: `${'/(app)'}${'/(tabs)'}/home/form/[id]` | `/home/form/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(app)'}/player/[id]` | `/player/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/favorite${`?${string}` | `#${string}` | ''}` | `/favorite${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/settings/faq${`?${string}` | `#${string}` | ''}` | `/settings/faq${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/favorite` | `/favorite`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/settings/faq` | `/settings/faq`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/home/category/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/home/category/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/home/category/channel/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/home/category/channel/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/home/form/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/home/form/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/player/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/player/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(app)'}${'/(tabs)'}/home/category/[playlistId]` | `/home/category/[playlistId]`, params: Router.UnknownInputParams & { playlistId: string | number; } } | { pathname: `${'/(app)'}${'/(tabs)'}/home/category/channel/[categoryId]` | `/home/category/channel/[categoryId]`, params: Router.UnknownInputParams & { categoryId: string | number; } } | { pathname: `${'/(app)'}${'/(tabs)'}/home/form/[id]` | `/home/form/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/player/[id]` | `/player/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
